parser: babel-eslint
extends:
    - vkbansal
    - vkbansal/react
env:
    browser: true
rules:
    react/no-array-index-key: 0
    func-names: 0
    import/no-commonjs: 0
    global-require: 0
    arrow-parens: 0
